apiVersion: apps/v1
kind: Deployment
metadata:
  name: onmgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onmgr
  template:
    metadata:
      labels:
        app: onmgr
    spec:
      containers:
      - image: okteto.dev/onmgr:latest
        name: onmgr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "40aaaca6-4e3c-46ed-9d10-d92a5373ee72"
        - name: Vless_Path
          value: "/vlx12c2"
        - name: Vmess_UUID
          value: "40aaaca6-4e3c-46ed-9d10-d92a5373ee72"
        - name: Vmess_Path
          value: "/vmx12c2"
        - name: Share_Path
          value: "/v2link"
